[package]
name = "akshually"
description = "The Library for Smart Boys"
version = "0.1.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/patrickbucher/akshually"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
